site_name: Frosty Archives
copyright: Snowflake Nightingale
repo_name: freeze-dolphin/blog

theme:
  name: terminal
  favicon: assets/favicon.ico
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
  highlightjs: true
  hljs_style: "Nord"
  hljs_languages:
    - yaml
    - rust
    - clojure
    - java
    - json

markdown_extensions:
  # Python Markdown
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs

plugins:
  - search
