site_name: My Docs
copyright: Snowflake Nightingale
repo_name: freeze-dolphin/blog

theme:
  name: terminal
  favicon: assets/favicon.ico
  theme_style: dark
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extentions:
  - admonition

plugins:
  - search
